---
platform: linux

image_resource:
  type: docker-image
  source: 
         repository: nerdammer/hbase-phoenix
         

inputs:
- name: resource-tutorial

jobs:
  - task: run
    file: resource-tutorial/proj2/run_spark.yml
