resources:
- name: build-spark
  type: docker-image
  source:
    repository: gettyimages/spark
- name: build-hbase
  type: docker-image
  source:
    repository: nerdammer/hbase-phoenix
    

jobs:
- name: build
  plan:
  - get: build-spark
  - get: build-hbase
  - task: build
