---
platform: linux

resources:
- name: build-spark
  type: docker-image
  source:
    repository: gettyimages/spark
        
- name: build-hbase
  type: docker-image
  source:
    repository: nerdammer/hbase-phoenix
    

jobs:
- name: build
  plan:
  - get: build-spark
    trigger: false
  - get: build-hbase
    params: { bump: minor }
  - task: build-iph-ui
    config:
      platform: linux
      inputs:
      - name: build-spark
      - name: build-hbase
      - name: resource-tutorial
            
run:
 path: sh
 args:
      - -exc
      - |
      cd resource-tutorial/proj2
      chmod 777 run_h.sh
      ./run_h.sh
