---
platform: linux

resources:
- name: build-spark
  type: docker-image
  source:
    repository: gettyimages/spark

jobs:
- name: run
  plan:
  - get: resource-tutorial
  - task: build-iph-ui
    config:
       run:
        path: sh
        args:
           - -exc
           - |
             cd resource-tutorial/proj2
             chmod 777 run_h.sh
             ./run_h.sh
