---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
  - name: resource-tutorial

jobs:
- name: run-git
  public: true
  plan:
    run:
      path: resource-tutorial/proj2/create.sh
  
